### ISSUE TITLE
Updated to Ubuntu 15.04 having some issues

### ISSUE THREAD

**Issue by morriscode** [DanMcInerney/LANs.py#55]
[*] Running ARP scan to identify users on the network; this may take a minute - [nmap -sn -n 192.168.1.0/24]
[*] Running nbtscan to get Windows netbios names - [nbtscan 192.168.1.0/24]
[*] Enabling monitor mode [airmon-ng start wlan0]
Traceback (most recent call last):
  File "LANs.py", line 1603, in <module>
    LANsMain(args)
  File "LANs.py", line 186, in LANsMain
    au.users(IPprefix, routerIP)
  File "LANs.py", line 1092, in users
    sniff(iface=self.monmode, prn=self.pkt_cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down

**Comment by DanMcInerney** [comment]
Are you connected to a network?

**Comment by morriscode** [comment]
Yes.

**Comment by DanMcInerney** [comment]
K I'll see if I can reproduce when I get a chance.
