### ISSUE TITLE
[Errno 19] No such device

### ISSUE THREAD

**Issue by Lithium95** [DanMcInerney/LANs.py#60]
Keep getting this error...
Traceback (most recent call last):
  File "LANs.py", line 1220, in <module>
    LANsMain(args)
  File "LANs.py", line 176, in LANsMain
    au.users(IPprefix, routerIP)
  File "LANs.py", line 1086, in users
    sniff(iface=self.monmode, prn=self.pkt_cb, store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 593, in sniff
    **karg)]
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 488, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

**Comment by kamikazechaser** [comment]
Same error for me too

**Comment by AndreiRegiani** [comment]
+1 Exactly the same error here.
```
Ubuntu 16.10 / 64-bit
Python 2.7.12+
```

**Comment by bilobom** [comment]
+1 same error here 

 Ubuntu 16.04.2  / 64-bit
Python 2.7.12+

**Comment by DanMcInerney** [comment]
Yeah I've pretty much abandoned this project since MITMf.py and bettercap
are both just better versions of LANs.py.
