### ISSUE TITLE
What this error?

### ISSUE THREAD

**Issue by ZCKun** [DanMcInerney/LANs.py#65]
`Traceback (most recent call last):
  File "LANs.py", line 1597, in <module>
    LANsMain(args)
  File "LANs.py", line 302, in LANsMain
    Spoof().poison(routerIP, victimIP, routerMAC, victimMAC)
  File "LANs.py", line 313, in poison
    send(ARP(op=2, pdst=victimIP, psrc=routerIP, hwdst=victimMAC))
  File "/usr/lib/python2.7/dist-packages/scapy/base_classes.py", line 223, in __call__
    i.__init__(*args, **kargs)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 99, in __init__
    self.fields[f] = self.get_field(f).any2i(self, v)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 249, in any2i
    return self.h2i(pkt,x)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 230, in h2i
    x = Net(x)
  File "/usr/lib/python2.7/dist-packages/scapy/base_classes.py", line 77, in __init__
    self.parsed,self.netmask = self._parse_net(net)
  File "/usr/lib/python2.7/dist-packages/scapy/base_classes.py", line 71, in _parse_net
    tmp[0]=socket.gethostbyname(tmp[0])
socket.gaierror: [Errno -3] Temporary failure in name resolution
`

**Comment by oldkingcone** [comment]
It failed at name resolution. Take a lines specified by the error and see if in copying, you miss placed a colon or any spacing. Or if there is trailing white space when there shouldn't be. Other than that i have not messed around with this program enough to be able to really assert what the issue is. Hope that helps.
